version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: run.sh
      timeout: 600
      runas: root    