version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase... 
      - export LC_ALL="en_US.UTF-8"
      - locale-gen en_US en_US.UTF-8
      - dpkg-reconfigure locales      
  build:
    commands:
      - echo Build started on `date`
      - mvn install 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/myproject-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - run.sh
  discard-paths: yes